import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { RootLayoutProps } from "@/app/types";
import { Albert_Sans, Montserrat_Alternates } from "next/font/google";
import Image from "next/image";
import logoImage from "@/public/printforge-logo.png";
import "./globals.css";
import Link from "next/link";
const albertSans = Albert_Sans({
  subsets: ["latin"],
  display: "swap",
});

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat-alternates",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.className} ${montserratAlternates.variable}`}
      >
        <header className="w-full bg-white">
          <nav className="flex justify-between items-center px-4 py-6">
            <div className="relative">
              <Link href={"/"}>
                <Image src={logoImage} alt="PrintForge Logo" width={150} />
              </Link>
            </div>
            <ul className="flex items-center gap-3">
              <Link href={"/3d-models"}>
                <li>3D Models</li>
              </Link>
              <Link href={"/about"}>
                <li>About</li>
              </Link>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
